### ISSUE TITLE
Typings don't work in Plugins

### ISSUE THREAD

**Issue by mnaoumov** [Fevol/obsidian-typings#10]
Consider

```typescript
import 'obsidian-typings';
import { Plugin } from 'obsidian';

export default class TestPlugin extends Plugin {
    test() {
        window.app.metadataCache.getBacklinksForFile; // OK
        this.app.metadataCache.getBacklinksForFile; // Compile-error
    }
}
```

The reason for that is that `window.app` is augmented `App` interface, but `this.app` is the instance of vanilla `App` class.

```ts
/** @public */
declare global {
	/**
	 * Global reference to the app.
	 * @public
	 * @deprecated - Prefer not to use this value directly.
	 */
	var app: App;
}
```

```ts
/**
 * @public
 */
export abstract class Plugin extends Component {

    /**
     * @public
     */
    app: App;
```

I can't find how to make typings work for Plugins

**Comment by Fevol** [comment]
That is really odd, and I'm actually not really sure what even causes this. Does this also happen if you only have the basic `obsidian-d.ts` typings enabled?

Also, I don't know what your set-up is, but in my case, you do not need to import the `obsidian-typings` file anywhere. It just exists to tell TS that the types do in fact exist on the global scope. What happens if you comment/remove the import statement?

**Comment by mnaoumov** [comment]
Fixed in https://github.com/obsidian-typings/obsidian-typings/releases/tag/1.0.1
